# Generated by Django 6.0.1 on 2026-03-27 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0002_remove_child_image_url_child_image_and_more'),
        ('families', '0003_remove_family_image_url_family_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyColorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.IntegerField(choices=[(0, '0: #ff7f7f'), (1, '1: #ff7fbf'), (2, '2: #ffbcff'), (3, '3: #bf7fff'), (4, '4: #7f7fff'), (5, '5: #7fbfff'), (6, '6: #7fffff'), (7, '7: #99ffcc'), (8, '8: #7fff7f'), (9, '9: #bfff7f'), (10, '10: #ffff7f'), (11, '11: #ffbf7f'), (12, '12: #c2bbb2')])),
                ('assign_type', models.IntegerField(choices=[(0, '合同'), (1, '大人'), (2, '子ども')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_assignments', to='children.child')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_assignments', to='families.family')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('family', 'color_code'), name='unique_family_color_code'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user',), name='unique_color_assignment_per_user'), models.UniqueConstraint(condition=models.Q(('child__isnull', False)), fields=('child',), name='unique_color_assignment_per_child'), models.UniqueConstraint(condition=models.Q(('assign_type', 0)), fields=('family', 'assign_type'), name='unique_shared_color_per_family')],
            },
        ),
    ]
