# Generated by Django 6.0.1 on 2026-04-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_email_alter_user_family_alter_user_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_seen_family_setup_completed',
            field=models.BooleanField(default=False),
        ),
    ]
