# Generated by Django 6.0.1 on 2026-03-20 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
        ('families', '0003_remove_family_image_url_family_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='image_url',
        ),
        migrations.AddField(
            model_name='child',
            name='image',
            field=models.ImageField(default='children/default.png', upload_to='children/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='child',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='families.family'),
        ),
        migrations.AlterField(
            model_name='child',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='child',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
