# Generated by Django 6.0.1 on 2026-02-22 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0002_alter_family_image_url_alter_family_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('memo', models.CharField(blank=True, max_length=300)),
                ('is_all_day', models.BooleanField(default=False)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('requires_coordination', models.BooleanField(default=False)),
                ('coordination_type', models.PositiveSmallIntegerField(blank=True, choices=[(0, '欠席対応'), (1, 'ケア(体調)'), (2, '送迎'), (3, 'サポート'), (4, 'その他')], null=True)),
                ('coordination_other_detail', models.CharField(blank=True, max_length=100)),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(0, '〇 確定(了承済)'), (1, '△ 調整中(返事待ち)'), (2, '✕ 不可')], null=True)),
                ('is_consecutive_coordination', models.BooleanField(default=False)),
                ('coordination_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='families.family')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
