# Generated by Django 6.0.1 on 2026-02-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='image_url',
            field=models.CharField(blank=True, max_length=300, verbose_name='家族アイコン'),
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='家族名'),
        ),
    ]
