# Generated by Django 6.0.1 on 2026-03-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_alter_family_image_url_alter_family_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='image_url',
        ),
        migrations.AddField(
            model_name='family',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='families/'),
        ),
        migrations.AlterField(
            model_name='family',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='family',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
