# Generated by Django 6.0.1 on 2026-05-04 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0002_remove_child_image_url_child_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('is_absent', models.BooleanField(default=False)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_records', to='children.child')),
            ],
            options={
                'ordering': ['-record_date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('child', 'record_date'), name='unique_absence_record_per_child_per_date')],
            },
        ),
        migrations.CreateModel(
            name='BowelMovementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('has_bowel_movement', models.BooleanField(default=False)),
                ('memo', models.TextField(blank=True)),
                ('has_concern', models.BooleanField(default=False)),
                ('concern_memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowel_movement_records', to='children.child')),
            ],
            options={
                'ordering': ['-record_date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('child', 'record_date'), name='unique_bowel_movement_record_per_child_per_date')],
            },
        ),
    ]
