# Generated by Django 6.0.1 on 2026-03-21 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0003_remove_family_image_url_family_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_token', models.CharField(max_length=300, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '未使用'), (1, '使用済'), (2, '期限切れ')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='families.family')),
            ],
        ),
    ]
