# Generated by Django 6.0.1 on 2026-05-10 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='absence_attachments/')),
                ('file_name', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('absence_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='records.absencerecord')),
            ],
        ),
        migrations.CreateModel(
            name='BowelMovementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bowel_movement_attachments/')),
                ('file_name', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bowel_movement_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='records.bowelmovementrecord')),
            ],
        ),
    ]
